stages:
- name: build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn -B -DskipTests clean package
- name: test
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn test
- name: deploy
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: sh ./jenkins/scripts/deliver.sh
timeout: 60
notification: {}
