stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn clean install
    when:
      branch:
        include:
        - master
- name: deploy
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: echo "完成部署测试！"
    env:
      JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk
      M2_HOME: /root/apache-maven-3.5.4
    when:
      branch:
        include:
        - master
timeout: 60
branch:
  include:
  - master
notification: {}
