stages:
- name: build
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: '''echo "building"'''
- name: test
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: '''mvn test'''
- name: deploy
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: '''./jenkins/scripts/deliver.sh'''
timeout: 60
notification: {}
