stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn clean install
- name: deploy
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: ./jenkins/scripts/deliver.sh
timeout: 60
notification: {}
